// Generated by CoffeeScript 1.12.2
(function () {
    var runner;

    runner = function () {
        var cmpserver, debug, exclusions, exts, opts, path, pjson, port, resolve, server, start, usePolling, version;
        pjson = require('../package.json');
        version = pjson.version;
        cmpserver = require('./cmpserver');
        shellserver = require('./shellserver');
        resolve = require('path').resolve;
        opts = require('opts');
        debug = false;
        opts.parse([{
            short: "v",
            long: "version",
            description: "Show the version",
            required: false,
            callback: function () {
                console.log(version);
                return process.exit(1);
            }
        }, {
            short: "p",
            long: "port",
            description: "Specify the port",
            value: true,
            required: false
        }, {
            short: "s",
            long: "start",
            description: "auto start cmpAPP page or not, default set true to start cmp, other value not start",
            value: true,
            required: false
        }, {
            short: "x",
            long: "exclusions",
            description: "Exclude files by specifying an array of regular expressions. Will be appended to default value which is []",
            required: false,
            value: true
        }, {
            short: "d",
            long: "debug",
            description: "Additional debugging information",
            required: false,
            callback: function () {
                return debug = true;
            }
        }, {
            short: "ss",
            long: "shell",
            description: "start shell server or not, default set true to start cmp, other value not start",
            required: false,
            callback: function () {
                return debug = true;
            }
        }].reverse(), true);
        port = opts.get('port') || 80;
        start = opts.get('start') || "true";
        exclusions = opts.get('exclusions') || [];
        exts = (opts.get('exts') || '').split(' ');
        shell = opts.get('shell') || "false";
        path = resolve(process.argv[2] || '.');
        server = cmpserver.createServer({
            port: port,
            start: start,
            debug: debug,
            exclusions: exclusions,
            exts: exts,
            path: path
        });
        if (shell == "true") {
            let shellPort = parseInt(port) + 1;
            shellserver.createServer(shellPort);
            console.log("Starting shellserver v" + version + " for " + path + " , port: " + shellPort + " ......");
        }
        return console.log("Starting cmpserver v" + version + " for " + path + " ......");
    };

    module.exports = {
        run: runner
    };

}).call(this);
